import type { Project } from './types';

export const SEED_PROJECT: Project = {
  version: 1,
  teams: [
    // Root org
    {
      id: 'org-acme',
      name: 'Acme Corp',
      parentId: null,
      space: { x: 0, y: 0, w: 0, h: 0 },
    },
    // Departments
    {
      id: 'dept-security',
      name: 'Security',
      parentId: 'org-acme',
      space: { x: 0, y: 0, w: 0, h: 0 },
    },
    {
      id: 'dept-engineering',
      name: 'Engineering',
      parentId: 'org-acme',
      space: { x: 0, y: 0, w: 0, h: 0 },
    },
    // Teams (leaf nodes with spaces)
    {
      id: 'team-security',
      name: 'Security Team',
      parentId: 'dept-security',
      currentTaskLabel: 'Find exploit in auth service',
      space: { x: 60, y: 60, w: 1350, h: 480 },
    },
    {
      id: 'team-backend',
      name: 'Backend Team',
      parentId: 'dept-engineering',
      currentTaskLabel: 'Implement rate-limiting feature',
      space: { x: 60, y: 620, w: 1350, h: 520 },
    },
  ],
  nodes: [
    // Security Team - "Find exploit" pipeline
    {
      id: 'n-sec-1',
      graphId: 'graph-security',
      teamId: 'team-security',
      type: 'inbox',
      name: 'Recon & Enumeration',
      status: 'done',
      priority: 'high',
      progress: 100,
      position: { x: 60, y: 160 },   // pitch 320 → gap 110px
      prompt: {
        task: 'Enumerate all public-facing endpoints and identify attack surface. Focus on authentication, session management, and input handling.',
        refinements: [
          {
            ts: '2024-01-10T09:00:00Z',
            author: 'alice@acme.com',
            text: 'Also check for JWT misconfiguration.',
          },
        ],
        comments: [],
      },
      executor: {
        provider: 'mock',
        model: 'mock-v1',
        skills: ['recon', 'scanning'],
        tools: ['nmap', 'burpsuite'],
        maxIterations: 5,
      },
      context: {
        files: [{ path: 'src/auth/**', kind: 'glob' }],
        extra: 'Focus on the /api/v2 prefix',
      },
      owners: { author: 'alice@acme.com', responsible: ['alice@acme.com'] },
      inputs: [],
      output: {
        summary: 'Found 14 endpoints; 3 use deprecated JWT alg=none fallback.',
        results: [
          '/api/v2/login accepts alg=none JWT',
          '/api/v2/reset lacks rate limiting',
          'Session cookie missing HttpOnly flag',
        ],
        commands: ['curl -X POST /api/v2/login -H "alg: none"'],
        artifacts: ['recon-report.md'],
      },
      history: [],
      version: 1,
    },
    {
      id: 'n-sec-2',
      graphId: 'graph-security',
      teamId: 'team-security',
      type: 'worker',
      name: 'Exploit Analysis',
      status: 'running',
      priority: 'critical',
      progress: 55,
      position: { x: 380, y: 160 },
      prompt: {
        task: 'Analyze the vulnerabilities found in recon phase. Write proof-of-concept exploits for the top 3 findings.',
        refinements: [],
        comments: [
          {
            ts: '2024-01-10T10:30:00Z',
            author: 'bob@acme.com',
            text: 'Be careful with the JWT none-alg — test in staging only.',
          },
        ],
      },
      executor: {
        provider: 'bob',
        model: 'bob-4',
        skills: ['exploit-dev', 'pentest'],
        tools: ['metasploit', 'python'],
        maxIterations: 10,
      },
      context: {
        files: [
          { path: 'src/auth/jwt.ts', kind: 'file' },
          { path: 'src/auth/session.ts', kind: 'file' },
        ],
        extra: '',
      },
      owners: { author: 'bob@acme.com', responsible: ['bob@acme.com', 'alice@acme.com'] },
      inputs: [{ fromNodeId: 'n-sec-1', enabled: true }],
      output: { summary: '', results: [], commands: [], artifacts: [] },
      history: [],
      version: 1,
    },
    {
      id: 'n-sec-gate',
      graphId: 'graph-security',
      teamId: 'team-security',
      type: 'gate',
      name: 'Security Review Gate',
      status: 'queued',
      priority: 'high',
      progress: 0,
      position: { x: 700, y: 160 },
      prompt: {
        task: 'Review exploit analysis results. Approve if PoC is complete and risk is documented. Request changes if coverage is insufficient.',
        refinements: [],
        comments: [],
      },
      executor: {
        provider: 'mock',
        model: 'mock-v1',
        skills: [],
        tools: [],
        maxIterations: 1,
      },
      context: { files: [], extra: '' },
      owners: { author: 'carol@acme.com', responsible: ['carol@acme.com'] },
      inputs: [{ fromNodeId: 'n-sec-2', enabled: true }],
      output: { summary: '', results: [], commands: [], artifacts: [] },
      history: [],
      version: 1,
    },
    {
      id: 'n-sec-3',
      graphId: 'graph-security',
      teamId: 'team-security',
      type: 'worker',
      name: 'Write CVE Report',
      status: 'queued',
      priority: 'normal',
      progress: 0,
      position: { x: 1020, y: 160 },
      prompt: {
        task: 'Write a formal CVE report for the confirmed vulnerabilities. Follow CVSS 3.1 scoring and include remediation recommendations.',
        refinements: [],
        comments: [],
      },
      executor: {
        provider: 'mock',
        model: 'mock-v1',
        skills: ['technical-writing'],
        tools: ['markdown'],
        maxIterations: 3,
      },
      context: { files: [], extra: '' },
      owners: { author: 'alice@acme.com', responsible: ['alice@acme.com'] },
      inputs: [{ fromNodeId: 'n-sec-gate', enabled: true }],
      output: { summary: '', results: [], commands: [], artifacts: [] },
      history: [],
      version: 1,
    },

    // Backend Team - feature pipeline
    {
      id: 'n-be-1',
      graphId: 'graph-backend',
      teamId: 'team-backend',
      type: 'worker',
      name: 'Investigate Rate Limiting',
      status: 'done',
      priority: 'normal',
      progress: 100,
      position: { x: 60, y: 160 },   // pitch 320 → gap 110px
      prompt: {
        task: 'Research best practices for API rate limiting. Document options: Redis sliding window, token bucket, leaky bucket. Recommend implementation approach.',
        refinements: [],
        comments: [],
      },
      executor: {
        provider: 'mock',
        model: 'mock-v1',
        skills: ['research'],
        tools: ['web-search'],
        maxIterations: 3,
      },
      context: { files: [], extra: '' },
      owners: { author: 'dave@acme.com', responsible: ['dave@acme.com'] },
      inputs: [],
      output: {
        summary: 'Recommend Redis sliding window with 1000 req/min default.',
        results: ['Redis sliding window is best fit', 'Use ioredis client', 'Add X-RateLimit headers'],
        commands: [],
        artifacts: ['rate-limit-research.md'],
      },
      history: [],
      version: 1,
    },
    {
      id: 'n-be-2',
      graphId: 'graph-backend',
      teamId: 'team-backend',
      type: 'worker',
      name: 'Implement Rate Limiter',
      status: 'rework',
      priority: 'high',
      progress: 70,
      position: { x: 380, y: 160 },
      prompt: {
        task: 'Implement Redis sliding-window rate limiter middleware. Add X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset headers.',
        refinements: [
          {
            ts: '2024-01-11T14:00:00Z',
            author: 'eve@acme.com',
            text: 'Also handle 429 response body with retry-after.',
          },
        ],
        comments: [],
      },
      executor: {
        provider: 'bob',
        model: 'bob-4',
        skills: ['backend', 'redis'],
        tools: ['code-editor', 'terminal'],
        maxIterations: 8,
      },
      context: {
        files: [
          { path: 'src/middleware/**', kind: 'glob' },
          { path: 'src/config/redis.ts', kind: 'file' },
        ],
        extra: 'Project uses Express 5 + TypeScript strict mode',
      },
      owners: { author: 'dave@acme.com', responsible: ['dave@acme.com', 'eve@acme.com'] },
      inputs: [{ fromNodeId: 'n-be-1', enabled: true }],
      output: {
        summary: 'Rate limiter implemented but missing retry-after header.',
        results: ['src/middleware/rateLimiter.ts created', 'Redis key schema: rl:{userId}:{minute}'],
        commands: [],
        artifacts: ['src/middleware/rateLimiter.ts'],
      },
      history: [],
      version: 2,
    },
    {
      id: 'n-be-gate',
      graphId: 'graph-backend',
      teamId: 'team-backend',
      type: 'gate',
      name: 'Code Review Gate',
      status: 'queued',
      priority: 'normal',
      progress: 0,
      position: { x: 700, y: 160 },
      prompt: {
        task: 'Review the rate limiter implementation. Check code quality, error handling, test coverage, and header spec compliance.',
        refinements: [],
        comments: [],
      },
      executor: {
        provider: 'mock',
        model: 'mock-v1',
        skills: [],
        tools: [],
        maxIterations: 1,
      },
      context: { files: [], extra: '' },
      owners: { author: 'eve@acme.com', responsible: ['eve@acme.com'] },
      inputs: [{ fromNodeId: 'n-be-2', enabled: true }],
      output: { summary: '', results: [], commands: [], artifacts: [] },
      history: [],
      version: 1,
    },
    {
      id: 'n-be-3',
      graphId: 'graph-backend',
      teamId: 'team-backend',
      type: 'worker',
      name: 'Write Tests',
      status: 'queued',
      priority: 'normal',
      progress: 0,
      position: { x: 1020, y: 160 },
      prompt: {
        task: 'Write integration tests for the rate limiter middleware. Test sliding window behavior, header values, 429 responses, and Redis failure fallback.',
        refinements: [],
        comments: [],
      },
      executor: {
        provider: 'bob',
        model: 'bob-4',
        skills: ['testing', 'jest'],
        tools: ['code-editor'],
        maxIterations: 5,
      },
      context: {
        files: [
          { path: 'src/middleware/rateLimiter.ts', kind: 'file' },
          { path: 'tests/**', kind: 'glob' },
        ],
        extra: '',
      },
      owners: { author: 'frank@acme.com', responsible: ['frank@acme.com'] },
      inputs: [{ fromNodeId: 'n-be-gate', enabled: true }],
      output: { summary: '', results: [], commands: [], artifacts: [] },
      history: [],
      version: 1,
    },
  ],
  graphContexts: [
    {
      id: 'graph-security',
      teamId: 'team-security',
      goal: 'Find and document exploitable vulnerabilities in the auth service',
      repo: 'github.com/acme/auth-service',
      conventions: 'TypeScript strict, ESLint airbnb, OWASP guidelines',
    },
    {
      id: 'graph-backend',
      teamId: 'team-backend',
      goal: 'Implement Redis-backed API rate limiting feature',
      repo: 'github.com/acme/backend-api',
      conventions: 'TypeScript strict, Express 5, Jest for tests',
    },
  ],
  templates: [
    {
      id: 'tpl-code-review',
      name: 'Code Review',
      description: 'Review code for quality, security, and best practices',
      isBuiltIn: true,
      defaults: {
        type: 'gate',
        priority: 'normal',
        prompt: {
          task: 'Review the provided code changes. Check for correctness, security issues, performance, code style, and test coverage. Approve or request changes.',
          refinements: [],
          comments: [],
        },
        executor: { provider: 'bob', model: 'bob-4', skills: ['code-review'], tools: ['code-editor'], maxIterations: 3 },
        context: { files: [], extra: '' },
      },
    },
    {
      id: 'tpl-write-tests',
      name: 'Write Tests',
      description: 'Generate comprehensive tests for a module',
      isBuiltIn: true,
      defaults: {
        type: 'worker',
        priority: 'normal',
        prompt: {
          task: 'Write comprehensive unit and integration tests. Aim for >80% coverage. Include happy path, edge cases, and error scenarios.',
          refinements: [],
          comments: [],
        },
        executor: { provider: 'bob', model: 'bob-4', skills: ['testing'], tools: ['code-editor', 'terminal'], maxIterations: 5 },
        context: { files: [], extra: '' },
      },
    },
    {
      id: 'tpl-fix-bug',
      name: 'Fix Bug',
      description: 'Diagnose and fix a reported bug',
      isBuiltIn: true,
      defaults: {
        type: 'worker',
        priority: 'high',
        prompt: {
          task: 'Diagnose the reported bug. Find root cause, implement fix, ensure no regression. Document the fix in the commit message.',
          refinements: [],
          comments: [],
        },
        executor: { provider: 'bob', model: 'bob-4', skills: ['debugging', 'backend'], tools: ['code-editor', 'terminal', 'debugger'], maxIterations: 8 },
        context: { files: [], extra: '' },
      },
    },
    {
      id: 'tpl-investigate',
      name: 'Investigate',
      description: 'Research and document findings on a technical topic',
      isBuiltIn: true,
      defaults: {
        type: 'inbox',
        priority: 'normal',
        prompt: {
          task: 'Research the topic thoroughly. Compare at least 3 approaches. Document findings, trade-offs, and a clear recommendation.',
          refinements: [],
          comments: [],
        },
        executor: { provider: 'mock', model: 'mock-v1', skills: ['research'], tools: ['web-search'], maxIterations: 3 },
        context: { files: [], extra: '' },
      },
    },
  ],
};
